apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myfirstagrofile
  name: myfirstagrofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfirstagrofile
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myfirstagrofile
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
